use gca;

INSERT INTO books (title, released_year) values ("Clean Code", 2008);
INSERT INTO books (title, released_year) values ("Clean Architecture: A Craftsman's Guide to Software Structure and Design", 2017);
INSERT INTO books (title, released_year) values ("Clean Agile: Back to Basics", 2019);
INSERT INTO books (title, released_year) values ("The Pragmatic Programmer", 1999);
INSERT INTO books (title, released_year) values ("Pragmatic Thinking and Learning: Refactor Your Wetware", 2008);
INSERT INTO books (title, released_year) values ("Learn to Program using Minecraft Plugins with Bukkit", 2014);
INSERT INTO books (title, released_year) values ("Refactoring", 1999);
INSERT INTO books (title, released_year) values ("Planning Extreme Programming", 2000);
INSERT INTO books (title, released_year) values ("Test-Driven Development by Example", 2002);
INSERT INTO books (title, released_year) values ("JUnit Pocket Guide", 2004);
INSERT INTO books (title, released_year) values ("Implementation Patterns", 2008);

INSERT INTO book_rating (book_id, user_id, rating) values (1, 1, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (1, 12, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (1, 3, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (1, 44, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (1, 66, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (1, 13, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 41, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 32, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 38, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 11, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 46, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 27, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 48, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 6, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (2, 62, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (3, 41, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (3, 3, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (3, 99, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 35, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 14, 2);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 95, 1);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 26, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 87, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 66, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 42, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 81, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 88, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 96, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 80, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 84, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 83, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 5, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (4, 47 , 2);
INSERT INTO book_rating (book_id, user_id, rating) values (5, 55, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (5, 72, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (5, 25, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (6, 68, 2);
INSERT INTO book_rating (book_id, user_id, rating) values (6, 76, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (6, 65, 1);
INSERT INTO book_rating (book_id, user_id, rating) values (6, 96, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (6, 10, 2);
INSERT INTO book_rating (book_id, user_id, rating) values (6, 45, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 40, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 73, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 9, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 93, 1);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 38, 2);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 30, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 80, 2);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 81, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 50, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 22, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 95, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (7, 52, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (8, 58, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 16, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 47, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 96, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 22, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 79, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 70, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 9, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 73, 5);
INSERT INTO book_rating (book_id, user_id, rating) values (9, 26, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (10, 27, 3);
INSERT INTO book_rating (book_id, user_id, rating) values (10, 51, 4);
INSERT INTO book_rating (book_id, user_id, rating) values (10, 66, 2);
INSERT INTO book_rating (book_id, user_id, rating) values (10, 33, 3);